spring.application.name=Doctalk-backend
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/doctalk
spring.datasource.username=postgres
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.doctalk=DEBUG
file.upload-dir=./uploads