spring.application.name=Doctalk-backend
server.port=8090
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/doctalk
spring.datasource.username=postgres
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.doctalk=DEBUG
file.upload-dir=./uploads
gemini.api.key=AIzaSyC3lD2GRu2tHOzxOHMS6fTu0AS-ZAhL3k4
jwt.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.jwtExpirationMs=86400000